### ISSUE TITLE
example on how to execute... 

### ISSUE THREAD

**Issue by steamerja** [marcpabst/mp2rage-denoise#1]
Can you proved an example of a shell command to execute the mp2rage_robust_combination?

Jeff

**Comment by marcpabst** [comment]
Hi Jeff,

There curently is no special way to do this, but you could always just call something like this:
```bash
python -c 'from mp2rage_denoise import *; mp2rage_robust_combination("filename_uni", "filename_inv1", "filename_inv2", "filename_output", multiplying_factor)'
```

Just make sure that your call happens within an environment which contains all dependencies. If in doubt, run: 
```bash
pip install matplotlib nibabel numpy scipy nilearn
``` 

Everything above obviously assumes that a recent version of Python 3 is installed. :)

Best, 
Marc

**Comment by steamerja** [comment]
Perfect - that worked - thank you.

Jeff
